language: python
python:
  - 3.5

install:
  - cd tools/validate/; python setup.py install; cd ../../

script:
  - ls
  - sh ./test.sh

notifications:
  email:
    on_success: always
    on_failure: always